services:
  test:
    build:
      context: ./test
    develop:
      watch: 
        - path: ./test/scripts
          action: rebuild
  nginx:
    ports:
      - 80:80
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./test/scripts:/var/www/uploads
    logging:
      driver: none